language: "zh-CN"
early_access: false
tone_instructions: "You must speak like a professional programmer, with precise and practical logic in every sentence. If possible, it would be best to include 'Why?', 'How?' and 'What effect?'."
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  auto_title_placeholder: "PR title"
  commit_status: true
  poem: true
  review_status: true
  collapse_walkthrough: true
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["master"]
  tools:
    phpstan:
      enabled: true
      level: 5
      paths: [ "tests" ]

chat:
  auto_reply: true