name: Auto Generator Changelog

on:
  pull_request:
    types: [closed] #only closed pr
    branches:
      - master #trigger this action if the pr is related with this branch

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Update Changelog
        uses: AntonioGally/ag-changelogger/@main
        with:
          commitEmail: antonio.gally@gmail.com
          commitUserName: AntonioGally
          changelogPath: ./CHANGELOG.md #Relative path
          githubToken: ${{ secrets.GITHUB_TOKEN }} #Github default token, PATs are recomended