name: Pierre-Review

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  auto:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Pierre-Review
        uses: aummo/pierre-review@main
      - name: PR Review & Summary Bot with AI and Chat Features Experimental
        uses: primathontech/primathon-ai-code-reviewer-experimental@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: true
          review_comment_lgtm: true
      - name: Run PR Auto on initial open PR
        if: github.event_name == 'pull_request'
        id: pr_auto_id
        uses: vblagoje/pr-auto@v1
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          user_prompt: ${{ github.event.pull_request.body }}
      - name: Update PR description
        uses: vblagoje/update-pr@v1
        with:
          pr-body: ${{ steps.pr_auto_id.outputs.pr-text }}